# Generated by Django 5.2.8 on 2026-01-26 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        help_text="Medical report (PDF/Image)",
                        upload_to="reports/%Y/%m/%d/",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of report (e.g., Blood Test, Ultrasound)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary from Gemini API",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Patient who uploaded this report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Report",
                "verbose_name_plural": "Medical Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "emergency_contact_email",
                    models.EmailField(
                        help_text="Email for emergency notifications", max_length=254
                    ),
                ),
                (
                    "due_date",
                    models.DateField(help_text="Expected due date of delivery"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="HealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        help_text="Age of the patient (18-70 years)",
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(70),
                        ],
                    ),
                ),
                (
                    "systolic_bp",
                    models.IntegerField(
                        help_text="Upper blood pressure value (mmHg)",
                        validators=[
                            django.core.validators.MinValueValidator(70),
                            django.core.validators.MaxValueValidator(220),
                        ],
                        verbose_name="Systolic Blood Pressure",
                    ),
                ),
                (
                    "diastolic_bp",
                    models.IntegerField(
                        help_text="Lower blood pressure value (mmHg)",
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(140),
                        ],
                        verbose_name="Diastolic Blood Pressure",
                    ),
                ),
                (
                    "bs",
                    models.FloatField(
                        help_text="Blood glucose level (mmol/L)",
                        validators=[
                            django.core.validators.MinValueValidator(4.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="Blood Glucose",
                    ),
                ),
                (
                    "body_temp",
                    models.FloatField(
                        help_text="Body temperature (°F)",
                        validators=[
                            django.core.validators.MinValueValidator(95.0),
                            django.core.validators.MaxValueValidator(105.0),
                        ],
                        verbose_name="Body Temperature",
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        help_text="Heart rate (beats per minute)",
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(140),
                        ],
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low risk", "Low Risk"),
                            ("mid risk", "Mid Risk"),
                            ("high risk", "High Risk"),
                        ],
                        help_text="AI-predicted risk level",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional observations", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Patient associated with this health log",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Log",
                "verbose_name_plural": "Health Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_health_timesta_2f8a5d_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="core_health_user_id_e152f2_idx",
                    ),
                ],
            },
        ),
    ]
