# Generated by Django 5.2.8 on 2026-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userprofile_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalreport",
            name="requires_doctor_review",
            field=models.BooleanField(
                default=False,
                help_text="Flag indicating if abnormalities were detected requiring doctor review",
            ),
        ),
        migrations.AddField(
            model_name="medicalreport",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("caution", "Caution"),
                    ("alert", "Alert"),
                ],
                default="normal",
                help_text="AI-assessed risk level from report",
                max_length=20,
            ),
        ),
    ]
